HF technical accuracy audit: Staking & Snarking
o1-labs/docs2 pull request #539
Opened 2023-07-26 13:47 UTC by barriebyron

A user reported the set-staking subcommand is in the docs, but does not show in mina client command line help.

While I was reviewing the doc, I improved the content in preparation for ITN and HF. Please review for thoroughness and technical accuracy.

Related:
https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/538

2023-07-26 13:49 UTC, barriebyron commented on docs/node-operators/staking-and-snarking.mdx
> +Delegating MINA has the benefit of not having to maintain a node that is always connected to the network.
```suggestion
Delegating MINA has the benefit of not having to maintain a node that is always connected to the network. See [Mina Foundation Delegation Program](/node-operators/foundation-delegation-program).
```

2023-07-26 14:05 UTC, barriebyron commented on docs/node-operators/staking-and-snarking.mdx
> +mina client set-staking --public-key $MINA_PUBLIC_KEY
protocol team, please verify that the set-staking subcommand is present in the command line help 
(or we can update the doc and instructions if the workflow is changed)

2023-07-28 21:07 UTC, deepthiskumar requested changes
`delegate-stake` is already part of the section for delegating stake. The set-staking section for staking one's own mina, aka, running block producer nodes. There was a command before to 
1. Enable staking on a node that did not have staking (using daemon command flags `--block-producer-key` or `--block-producer-pubkey`) 
or 
2. Change the public key with which validators wanted to stake 

We should simply remove the `set-staking` option and keep only the
`you can restart the daemon with the -block-producer-pubkey flag:` part as shown in the doc currently https://docs.minaprotocol.com/node-operators/staking-and-snarking

2023-08-02 16:06 UTC, barriebyron commented
thanks @deepthiskumar  for that feedback, see changes for approval please

2023-08-02 16:23 UTC, barriebyron commented
issue for the incorrect Mina Client CLI doc https://github.com/MinaProtocol/mina/issues/13820

2023-08-14 16:09 UTC, barriebyron commented on docs/node-operators/staking-and-snarking.mdx
> +Use the `mina client delegate-stake` subcommand to set or change the block producer key. See the [Mina Client](/node-operators/mina-cli-reference#mina-client) CLI help.
great @georgeee  much clearer

2023-08-14 16:11 UTC, georgeee approved these changes

2023-08-14 16:11 UTC, georgeee commented on docs/node-operators/staking-and-snarking.mdx
> +You can interact with the Mina network by participating in consensus and helping compress data by generating zk-SNARKs. By operating a node that helps secure the network, you can receive MINA for you
I would propose to change "compress" to something more like "produce a cryptographic proof for the data".

Compression is only a very imprecise analogy.

2023-08-14 16:37 UTC, barriebyron commented on docs/node-operators/staking-and-snarking.mdx
> +You can interact with the Mina network by participating in consensus and helping compress data by generating zk-SNARKs. By operating a node that helps secure the network, you can receive MINA for you
```suggestion
You can interact with the Mina network by participating in consensus to produce a cryptographic proof for the data by generating zk-SNARKs. By operating a node that helps secure the network, you can receive MINA for your efforts. See [Staking Rewards on Mina](https://minaprotocol.com/blog/staking-rewards-on-mina).
```

2023-08-14 20:35 UTC, bkase approved these changes
I did a quick skim, looks good!

2023-08-14 21:29 UTC, barriebyron commented
@bkase thank you for approval... hmmm, still can't merge. can you help me unblock this PR?

> Merging is blocked
> Merging can be performed automatically once the requested changes are addressed.

2023-10-02 18:20 UTC, deepthiskumar commented on docs/node-operators/staking-and-snarking.mdx
> +Use the `mina client delegate-stake` subcommand to set or change delegation of the block producer key. See the [Mina Client](/node-operators/mina-cli-reference#mina-client) CLI help.
I think it is better to point to the `Delegating MINA` that follows this section and which has more information about delegating

2023-10-02 18:20 UTC, deepthiskumar approved these changes
Made a suggestion but otherwise lgtm

2023-10-02 20:33 UTC, barriebyron commented on docs/node-operators/staking-and-snarking.mdx
> +Use the `mina client delegate-stake` subcommand to set or change delegation of the block producer key. See the [Mina Client](/node-operators/mina-cli-reference#mina-client) CLI help.
```suggestion
Use the `mina client delegate-stake` subcommand to set or change the delegation of the block producer key. See
 [Delegating MINA](#delegating-mina).
```

2023-10-02 20:34 UTC, merged