docs: getting started zkApps
o1-labs/docs2 pull request #632
Opened 2023-10-09 20:53 UTC by barriebyron

For #630 
This PR 
- creates a standalone zkApp-focused zkApp Developer Getting Started 
- moves the installation content from https://docs.minaprotocol.com/zkapps#quickstart from overview to a new installation page to create a canonical installation and upgrade page for zkApp CLI 

audience: devs who want to use zkApps and zkApp CLI

2023-10-10 18:02 UTC, nicc requested changes

2023-10-10 18:56 UTC, barriebyron commented on docs/zkapps/getting-started-zkapps.mdx
> +1. Create a local blockchain instance to interact with.
@nicc  happy to make changes when I know something is a code literal - sometimes, I just don't know (yet)

2023-10-10 18:57 UTC, barriebyron commented on docs/zkapps/getting-started-zkapps.mdx
> +    See [Deploying a contract locally](https://docs.minaprotocol.com/zkapps/how-to-test-a-zkapp#deploying-a-contract-locally).
TIL copy-pasta

2023-10-11 19:05 UTC, ymekuria approved these changes
This is a work in progress and we will continue to iterate to make this more comprehensive.

2023-10-11 19:05 UTC, barriebyron commented
We look forward to getting feedback from devs! This Getting Started deliverable is the first iteration of awesomeness to grow and improve!

2023-10-12 11:15 UTC, nicc approved these changes

2023-10-12 11:15 UTC, nicc commented on docs/zkapps/getting-started-zkapps.mdx
> +1. In o1js, an array of 10 test accounts to pay fees and sign transactions are provided for the `LocalBlockchain` instance in the `Local.testAccounts;` in the [Add.test.ts](https://github.com/o1-labs
```suggestion
1. In o1js, an array of 10 test accounts to pay fees and sign transactions are provided for the `LocalBlockchain` instance. These can be accessed with `Local.testAccounts` as per the [Add.test.ts](https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L29-L31) example file. The example uses the public/private key pairs of two of these accounts. They are given these names, but the names can be anything:
```

2023-10-12 11:15 UTC, nicc commented on docs/zkapps/getting-started-zkapps.mdx
> +1. Start experimenting with iterative development to build and test one method at a time. Add functionality to the smart contract by implementing an `@method`.
```suggestion
1. Start experimenting with iterative development to build and test one method at a time. Add functionality to the smart contract by implementing a `@method`.
```
I think? Feels better to me anyway

2023-10-12 11:15 UTC, nicc commented on docs/zkapps/getting-started-zkapps.mdx
> +1. Configure your zkapp.
```suggestion
1. Configure your zkApp.
```

2023-10-13 11:34 UTC, merged