docs: glossary zkApp account, zkApp Manager account
o1-labs/docs2 pull request #674
Opened 2023-10-20 18:39 UTC by barriebyron

This PR adds two new terms to the glossary

Esp interested in @garwalsh's feedback on the capitalization and "productization" of the term: zkApp Manager account
Choices:
- zkApp Manager account
- zkApp manager account
Or?

2023-10-20 20:21 UTC, barriebyron commented on docs/glossary.mdx
> +### zkApp Manager account
```suggestion
### zkApp manager account
```

2023-10-31 20:35 UTC, garwalsh requested changes
zkApp Manager is capitalised in the description, otherwise lgtm!

2023-11-01 13:07 UTC, barriebyron commented on docs/glossary.mdx
> +A specific type of smart contract that manages a particular thing. For example, the zkApp Manager account for a token controls all properties of token accounts and determines rules for token minting,
```suggestion
A specific type of smart contract that manages a particular thing. For example, the zkApp manager account for a token controls all properties of token accounts and determines rules for token minting, burning, and transfer.
```

2023-11-01 13:09 UTC, barriebyron commented
Thanks @garwalsh  back to you.

2023-11-01 13:27 UTC, garwalsh approved these changes

2023-11-01 13:31 UTC, merged