improve tutorial 4
o1-labs/docs2 pull request #693
Opened 2023-10-27 14:36 UTC by qwadratic

[Tutorial 4](https://docs.minaprotocol.com/zkapps/tutorials/zkapp-ui-with-react) uses the [hardcoded zkApp address](https://github.com/o1-labs/docs2/blob/e2248ea9b804a64f1951727b02b908fdb71ad4fb/examples/zkapps/04-zkapp-browser-ui/ui/src/pages/index.page.tsx#L79), but due to Berkeley reloads, it's better to add a note that a user should deploy contract first. Also zkapp address is better to be defined as const on top of the `index.tsx` file

2023-10-28 21:24 UTC, barriebyron commented on docs/zkapps/tutorials/04-zkapp-ui-with-react.mdx
> +You will likely need to deploy the zkApp to Berkeley yourself, as this network is sometimes being reloaded. When deployed, replace the `ZKAPP_ADDRESS` with the address of your deployment.
```suggestion
For best results, deploy the zkApp to Berkeley yourself, as this test network is sometimes being reloaded. When deployed, replace `ZKAPP_ADDRESS` with the address of your deployment.
```

2023-10-28 21:25 UTC, barriebyron commented on docs/zkapps/tutorials/04-zkapp-ui-with-react.mdx
> +export default function Home() {
thanks for these updates @qwadratic 
I defer to  @ymekuria for the code update review and to verify that the tutorial runner does not have line number dependencies

2023-10-28 21:27 UTC, barriebyron commented on docs/zkapps/tutorials/04-zkapp-ui-with-react.mdx
> +export default function Home() {
@ymekuria  can you also evaluate https://github.com/o1-labs/docs2/issues/694

2023-11-14 10:59 UTC, ymekuria requested changes
I left a suggestion. I think it is a good idea to suggest deploying to Berkeley but suggested a change to how we present that option.

2023-11-14 10:59 UTC, ymekuria commented on docs/zkapps/tutorials/04-zkapp-ui-with-react.mdx
> +For best results, deploy the zkApp to Berkeley yourself, as this test network is sometimes being reloaded. When deployed, replace `ZKAPP_ADDRESS` with the address of your deployment.
```suggestion
The smart contract that the UI interacts with in this tutorial has been deployed to the Berkeley network and the public key is stored as the `ZKAPP_ADDRESS` in the UI project. If you experience problems with the deployed contract, you can deploy the `Add` contract included in the `contracts` folder yourself to the Berkeley network. When deployed, replace `ZKAPP_ADDRESS` with the  public key of your deployment.
```

2023-11-14 15:52 UTC, ymekuria approved these changes
LGTM! Thanks.

2023-11-14 15:52 UTC, merged