#749  Rename deprecated assert* to require* in o1js precondition APIs
o1-labs/docs2 pull request #786
Opened 2023-12-20 07:19 UTC by LuffySama-Dev

Hi @mitschabaude , @ymekuria , @barriebyron ,

Please find the below changes that I have made to close the issue number #749 .

**Changes Made:**

- Renamed deprecated assert* with require*
- Updated the tutorials package.json to use latest o1js version

**Files/Tutorials changed:**

- Examples from 01 to 11 and Interacting with zkapps are updated
- Tutorials from 01 to Interacting with zkapps are updated
- Other documentations where also updated

**Files/Tutorials Pending to be updated:**

- Facing issue with example 06-offchain-storage. I have updated it locally but the offchain storage zkApp contract's package.json has peer dependency to version of "experimental-offchain-zkapp-storage". So I think we need to update it so, I will need your guidance over here on what to change and how. cc: @mitschabaude 
- Anonymous message board has not used assert for state so no changes made but, I have locally updated it's package.json to use latest o1js version. My question is should I commit it or not ?
- o1js-reference is the only folder I am yet to go through so will make changes to it soon.

Thank You
Luffy 😃

2023-12-20 18:48 UTC, ymekuria requested changes
Thanks for making these changes @LuffySama-Dev! Could you update the `o1js` version to `0.15.1` in all the tutorials?

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/01-hello-world/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/02-private-inputs-and-hash-functions/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/04-zkapp-browser-ui/contracts/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/05-common-types-and-functions/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/07-oracles/contracts/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/08-custom-tokens/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/09-recursion/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/10-account-updates/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/11-advanced-account-updates/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-20 18:48 UTC, ymekuria commented on examples/zkapps/interacting-with-zkApps-server-side/package.json
> +    "o1js": "0.15.0"
```suggestion
    "o1js": "0.15.1"
```

2023-12-21 13:17 UTC, LuffySama-Dev commented
Hi @ymekuria ,

Yes sure!

Thanks

2023-12-21 13:36 UTC, LuffySama-Dev commented
Hi @ymekuria ,

I have made changes as requested.

Thanks 😃

2024-01-04 08:25 UTC, ymekuria approved these changes
Thanks @LuffySama-Dev !

2024-01-04 08:31 UTC, merged