fix: Lightnet docs
o1-labs/docs2 pull request #825
Opened 2024-02-02 21:14 UTC by barriebyron

This PR closes https://github.com/o1-labs/docs2/issues/821 with fixes to the Lightnet docs

Thank you @Sventimir  for the detailed suggestions for updates

2024-02-02 21:28 UTC, barriebyron commented on docs/zkapps/testing-zkapps-lightnet.mdx
> +- Starts the Mina archive process and the [archive-node-API](https://github.com/o1-labs/Archive-Node-API) application.
```suggestion
- Starts the Mina archive process and the [Archive-Node-API](https://github.com/o1-labs/Archive-Node-API) application.
```

2024-02-03 17:03 UTC, shimkiv requested changes

2024-02-03 17:03 UTC, shimkiv commented on docs/zkapps/testing-zkapps-lightnet.mdx
> +zk lightnet explorer list
```suggestion
zk lightnet explorer --list
```

2024-02-03 17:03 UTC, shimkiv commented on docs/zkapps/testing-zkapps-lightnet.mdx
> +This command downloads and updates a lightweight Mina explorer. By default, the latest version is downloaded (if needed) and launched.
```suggestion
By default, this command downloads (if needed) and launches the latest version of [lightweight Mina explorer](https://github.com/o1-labs/mina-lightweight-explorer). 
```

2024-02-05 21:46 UTC, barriebyron commented on docs/zkapps/testing-zkapps-lightnet.mdx
>  1. [Write tests for your smart contract](/zkapps/testing-zkapps-locally#writing-tests-for-your-smart-contract).
Yes, it's fine https://github.com/o1-labs/docs2/wiki/Markdown-Syntax#numbered-steps 
Using 1. for each step simplifies maintenance
Here's the handy preview link https://docs2-git-iterate-lightnet-minadocs.vercel.app/zkapps/testing-zkapps-lightnet#prerequisites

2024-02-05 21:46 UTC, barriebyron commented on docs/zkapps/testing-zkapps-lightnet.mdx
> +The best way experience Lightnet is by using it from the zkApp CLI command line.
oof thankies eagle eye!

2024-02-06 12:20 UTC, shimkiv approved these changes

2024-02-06 17:31 UTC, merged