Added oracle example
o1-labs/docs2 pull request #86
Opened 2022-10-28 00:16 UTC by jackryanservia

2022-11-01 00:00 UTC, garethtdavies commented on docs/zkapps/tutorials/oracle.mdx
> +The zkApp CLI automatically generated a file called `CreditScoreOracle.test.ts` for us when we ran `zk file CreditScoreOracle`. Let’s add some tests. Open it and paste in the following:
This should be `zk file CreditScoreVerifier` and `CreditScoreVerifier.test.ts` to match the `zk file` command from earlier.

2022-11-03 23:25 UTC, etekis requested changes

2022-11-03 23:25 UTC, etekis commented on docs/zkapps/tutorials/oracle.mdx
> +
This also allows for data providers themselves to sign the data, without the zkApp developer having to fetch and act as an intermediary. In this way, when a KYC or credit score provider starts to sign their API calls, zkApp developers can easily consume that data while ensuring it is from the expected source.

2022-11-15 00:48 UTC, jackryanservia reviewed
Added a note box to explain that data providers can also operate response signers so that users don't have to trust an intermediary party.

2022-11-16 23:22 UTC, jasongitmail reviewed
This looks good, but we still should change the repo name to `oracle-example`.

2022-11-17 17:53 UTC, jasongitmail approved these changes
Approving and merging in the interest of time. But @jackryanservia please follow up with renaming the repo to `oracle-example`. Thanks!

2022-11-17 17:54 UTC, merged